title: Jeffrey Maher
description: Engineering Analyst and aspiring Computer Scientist
# Contact Info
email: maherje@oregonstate.edu
linkedin_url: https://www.linkedin.com/in/jeff-maher-6bb10958
theme: jekyll-theme-minimal
