title: Jeffrey Maher
description: Engineering Analyst and aspiring Computer Scientist
contact:
  email: "maherje@oregonstate.edu"
social_links:
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/jeff-maher-6bb10958"
theme: jekyll-theme-minimal
